sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eClZQrF87TBwChEPslvzqDQ4AvSR0qyyB6dLAJ0wqaxG9VgGMr87Jxi1Ysa6R50lbZoKpfOlpi6TNejpzrqxK3/cXJnzkq6mvTu9HxiaezrehTbFZ9VxWpGs6tpRZhtQPPj5bwNRKKtQA1MJ4EWBix7qUksqnS53wCqJHNaHaFEOGPsDbEktsNenP5ig+nWJpmISjVY6TvkArovWWTEopLEOU2PG0p/oLHoe+IJM/nyIVx9G3eB72Wrdldwn/V7zLLXo1ZcjB9INYLf23tAr6ODNRGOqNZiaPQGS+Gxe/qH1LPysH0Nu49iLUFEYG9T1i/WK4k3NvcD+SZJRqAWoTdmqRuGnijcBkebbsI2UNSKVTwfkzqmMaqdgdhYc0rzAE2MPl/1yIDx1A0hgWQ9Ut6D7Qd0vkkB/CypxAGWfxePO/YEWUnRjjJAzbSlk8cb7cF2Pw3aNCMqpR3XE3W5so9yRXbcGCtBZFsSuJ0zWZhqo7GrH7DhsgmquGZhsImhUhz/PPmWRrsEqPp4mBQdQGd5Os6ZUYtPtPjoFlh0bx20FcrBtd6+WP0uqvYYfNeeaZokIV1/y9sJbJuCmjrAMWO5t7jKKtKjS4u/fph75fY0ecg2CbkF5B41jnTpZz76gmawI6yO4iL0PHmtmnvG4oz2HcpvrYejhiRLf3LpMNYM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Rhoda-Fleming-Volume-2_4422
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy